-- 1) Create ENUM type for account roles
CREATE TYPE public.account_type AS ENUM
    ('Client', 'Employee', 'Admin');

ALTER TYPE public.account_type
    OWNER TO cse340_jqsb_user;

-- 2) Create classification table
CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name VARCHAR NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- 3) Create inventory table
CREATE TABLE IF NOT EXISTS public.inventory
(
    inv_id SERIAL PRIMARY KEY,
    inv_make VARCHAR(50) NOT NULL,
    inv_model VARCHAR(50) NOT NULL,
    inv_year INTEGER NOT NULL,
    inv_image VARCHAR(255) NOT NULL,
    inv_thumbnail VARCHAR(255) NOT NULL,
    inv_description TEXT NOT NULL,
    inv_color VARCHAR(30) NOT NULL,
    inv_name VARCHAR(100) NOT NULL,
    inv_price NUMERIC(9,2) NOT NULL,
    inv_miles INTEGER NOT NULL,
    classification_id INTEGER NOT NULL
);

-- 4) Create relationship between classification and inventory
ALTER TABLE IF EXISTS public.inventory
ADD CONSTRAINT fk_classification
FOREIGN KEY (classification_id)
REFERENCES public.classification (classification_id)
ON UPDATE CASCADE
ON DELETE NO ACTION;

-- 5) Create account table
CREATE TABLE IF NOT EXISTS public.account
(
    account_id INT GENERATED BY DEFAULT AS IDENTITY,
    account_firstname VARCHAR NOT NULL,
    account_lastname VARCHAR NOT NULL,
    account_email VARCHAR NOT NULL,
    account_password VARCHAR NOT NULL,
    account_type public.account_type NOT NULL DEFAULT 'Client',
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- 6) Insert sample data into classification
INSERT INTO public.classification (classification_name)
VALUES 
('Custom'),
('Sport'),
('SUV'),
('Truck'),
('Sedan');
-- Create ENUM type
CREATE TYPE account_role AS ENUM ('User', 'Admin');

-- Accounts table
CREATE TABLE account (
    account_id SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    account_type account_role DEFAULT 'User'
);

-- Classification table
CREATE TABLE classification (
    classification_id SERIAL PRIMARY KEY,
    classification_name VARCHAR(50) NOT NULL UNIQUE
);

-- Inventory table
CREATE TABLE inventory (
    inv_id SERIAL PRIMARY KEY,
    inv_make VARCHAR(50) NOT NULL,
    inv_model VARCHAR(50) NOT NULL,
    inv_description TEXT,
    inv_image VARCHAR(255),
    inv_thumbnail VARCHAR(255),
    classification_id INT NOT NULL,
    CONSTRAINT fk_classification FOREIGN KEY (classification_id)
        REFERENCES classification (classification_id)
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);

-- Insert data into classification
INSERT INTO classification (classification_name) VALUES
('SUV'), ('Truck'), ('Sport')
ON CONFLICT (classification_name) DO NOTHING;

-- Insert sample inventory dynamically
INSERT INTO inventory (inv_make, inv_model, inv_description, inv_image, inv_thumbnail, classification_id)
VALUES
('GM', 'Hummer', 'Known for small interiors', '/images/hummer.jpg', '/images/hummer-tn.jpg', 
 (SELECT classification_id FROM classification WHERE classification_name = 'SUV')),
('Ford', 'Raptor', 'High performance sport truck', '/images/raptor.jpg', '/images/raptor-tn.jpg',
 (SELECT classification_id FROM classification WHERE classification_name = 'Truck')),
('Chevy', 'Corvette', 'Sporty and fast', '/images/corvette.jpg', '/images/corvette-tn.jpg',
 (SELECT classification_id FROM classification WHERE classification_name = 'Sport'));

-- Task One query #4
UPDATE inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- Task One query #6
UPDATE inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');

