-- 1) Create ENUM type for account roles
CREATE TYPE public.account_type AS ENUM
    ('Client', 'Employee', 'Admin');

ALTER TYPE public.account_type
    OWNER TO cse340_jqsb_user;

-- 2) Create classification table
CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name VARCHAR NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- 3) Create inventory table
CREATE TABLE IF NOT EXISTS public.inventory
(
    inv_id SERIAL PRIMARY KEY,
    inv_make VARCHAR(50) NOT NULL,
    inv_model VARCHAR(50) NOT NULL,
    inv_year INTEGER NOT NULL,
    inv_image VARCHAR(255) NOT NULL,
    inv_thumbnail VARCHAR(255) NOT NULL,
    inv_description TEXT NOT NULL,
    inv_color VARCHAR(30) NOT NULL,
    inv_name VARCHAR(100) NOT NULL,
    inv_price NUMERIC(9,2) NOT NULL,
    inv_miles INTEGER NOT NULL,
    classification_id INTEGER NOT NULL
);

-- 4) Create relationship between classification and inventory
ALTER TABLE IF EXISTS public.inventory
ADD CONSTRAINT fk_classification
FOREIGN KEY (classification_id)
REFERENCES public.classification (classification_id)                      
ON UPDATE CASCADE
ON DELETE NO ACTION;

-- 5) Create account table
CREATE TABLE IF NOT EXISTS public.account
(
    account_id INT GENERATED BY DEFAULT AS IDENTITY,
    account_firstname VARCHAR NOT NULL,
    account_lastname VARCHAR NOT NULL,
    account_email VARCHAR NOT NULL,
    account_password VARCHAR NOT NULL,
    account_type public.account_type NOT NULL DEFAULT 'Client',
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- 6) Insert sample data into classification
INSERT INTO public.classification (classification_name)
VALUES 
('Custom'),
('Sport'),
('SUV'),
('Truck'),
('Sedan');

-- 1. Insert Tony Stark record
INSERT INTO public.account (account_firstname, account_lastname, account_email, account_password)
VALUES ('Tony', 'Stark', 'tony@starkent.com', 'Iam1ronM@n');

-- 2. Modify Tony Stark record to change account_type to "Admin"
UPDATE public.account
SET account_type = 'Admin'
WHERE account_firstname = 'Tony' AND account_lastname = 'Stark';

-- 3. Delete the Tony Stark record from the database
DELETE FROM public.account
WHERE account_firstname = 'Tony' AND account_lastname = 'Stark';

-- 4. Modify the "GM Hummer" record description
UPDATE public.inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- 5. Use inner join to select Sport category vehicles
SELECT inv_make, inv_model, classification_name
FROM public.inventory
INNER JOIN public.classification 
ON inventory.classification_id = classification.classification_id
WHERE classification_name = 'Sport';

-- 6. Update image paths to add "/vehicles"
UPDATE public.inventory
SET 
    inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');