CREATE TYPE public.account_type AS ENUM
    ('Client', 'Employee', 'Admin');

ALTER TYPE public.account_type
    OWNER TO cse340_jqsb_user;
--Table structure for table "classification"
CREATE TABLE public.classification (
classification-id INT GENERATED BY DEFAULT AS IDENTITY, 
classification-name CHARACTER VARYING NOT NULL,
CONTRAINT classification-pk PRIMARY KEY (classification-id)
);