--Table structure for table "account"
CREATE TYPE public.account_type AS ENUM
    ('Client', 'Employee', 'Admin');

ALTER TYPE public.account_type
    OWNER TO cse340_jqsb_user;
--Table structure for table "classification"
CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name VARCHAR NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

--Data for table 'classification'
INSERT INTO public.classification (classification_name)
VALUES ('Custom'),
('Sport'),
('SUV'),
('Truck'),
('Sedan');
--Data for table 'inventory'
ALTER TABLE IF EXISTS public.inventory
ADD CONSTRAINT fk_classification
FOREIGN KEY (classification_id)
REFERENCES public.classification (classification_id)
ON UPDATE CASCADE
ON DELETE NO ACTION;
-- Table structure for table `account`
CREATE TABLE IF NOT EXISTS public.account
(
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);