-- 1) Create ENUM type for account roles
CREATE TYPE public.account_type AS ENUM
    ('Client', 'Employee', 'Admin');

ALTER TYPE public.account_type
    OWNER TO cse340_jqsb_user;

-- 2) Create classification table
CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name VARCHAR NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- 3) Create inventory table
CREATE TABLE IF NOT EXISTS public.inventory
(
    inv_id SERIAL PRIMARY KEY,
    inv_make VARCHAR(50) NOT NULL,
    inv_model VARCHAR(50) NOT NULL,
    inv_year INTEGER NOT NULL,
    inv_image VARCHAR(255) NOT NULL,
    inv_thumbnail VARCHAR(255) NOT NULL,
    inv_description TEXT NOT NULL,
    inv_color VARCHAR(30) NOT NULL,
    inv_name VARCHAR(100) NOT NULL,
    inv_price NUMERIC(9,2) NOT NULL,
    inv_miles INTEGER NOT NULL,
    classification_id INTEGER NOT NULL
);

-- 4) Create relationship between classification and inventory
ALTER TABLE IF EXISTS public.inventory
ADD CONSTRAINT fk_classification
FOREIGN KEY (classification_id)
REFERENCES public.classification (classification_id)
ON UPDATE CASCADE
ON DELETE NO ACTION;

-- 5) Create account table
CREATE TABLE IF NOT EXISTS public.account
(
    account_id INT GENERATED BY DEFAULT AS IDENTITY,
    account_firstname VARCHAR NOT NULL,
    account_lastname VARCHAR NOT NULL,
    account_email VARCHAR NOT NULL,
    account_password VARCHAR NOT NULL,
    account_type public.account_type NOT NULL DEFAULT 'Client',
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- 6) Insert sample data into classification
INSERT INTO public.classification (classification_name)
VALUES 
('Custom'),
('Sport'),
('SUV'),
('Truck'),
('Sedan');

